dist: trusty
sudo: false
language: ruby
rvm:
  - 2.3
  - 2.2
  - 2.0
  - 1.9.3
gemfile:
  - Gemfile
  - gemfiles/message_driver_master.gemfile
  - gemfiles/message_driver_development.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/message_driver_development.gemfile
before_install:
  - gem install bundler
  - ruby -rubygems -e "if RUBY_VERSION > '2.2' && Gem::VERSION < '2.5.2'; exec 'gem update --system 2.5.2'; end"
bundler_args: --without tools
script: bundle exec rake
